4. Představme si metodu deflace, která ze spektra matice A odebere vlastní číslo λ. Tato metoda se dá zapsat jako **A_new = A−λ*v*v^T** .Použijte tuto metodu v kombinaci s implementaci
mocninné metody uvedené na přednáškách, resp. na cvičení, pro nalezení tří různých (v
ideálním případě největších) vlastních čísel vhodně zvolené matice A a naimplementujte
ji v programovacím jazyce Python. Můžete vyjít z následujícího pseudokódu:

        Input: matrix A, initial approximation x0, maximum number of iterations max_it.
        A_1 = A
        for j = 1,2,3
            q_0 = x0 / ∥x0∥
            for k = 1,2,...,max_it
                x_k = A_j * q_k−1
                q_k = x_k / ∥x_k∥
            end for
            λ_j = (q_k)^T * Aj * q_k
            v_j= q_k
            A_j+1 = A_j − λ_j *v_j * v_j^T (deflace)
        end for
        Output: λ1,λ2,λ3

In [37]:
import numpy as np

In [38]:
def power_method (A, x0, max_it = 3, tol = 1e-10, use_residual_stop = True, verbose = False):
    q = x0 / np.linalg.norm(x0)

    for k in range (1, max_it + 1):
        x = A @ q

        q = x / np.linalg.norm(x)

        lambda_k = q.T @ A @ q

        if verbose:
            print(f"Iterace {k}:")
            print(f"    x = {np.round(x, 3)}")
            print(f"    q = {np.round(q, 3)}")
            print(f"    lambda_k = {lambda_k:.3f}")
            if use_residual_stop:
                residual = np.linalg.norm(A @ q - lambda_k * q)
                if residual < tol:
                    break

    return lambda_k, q, k


In [39]:
def deflation_method (A, x0, max_it = 3, tol = 1e-10, verbose = False):
    n = A.shape[0]
    vlastni_cisla = []
    vlastni_vektory = []

    A_current = A.copy()

    for j in range (3):
        if j == 0:
            print(f"\n--- VLASTNI CISLO {j + 1} ---")
            lambda_j, q_j, k = power_method(A_current, x0, max_it, tol, verbose = verbose)
        else:
            lambda_j, q_j, k = power_method(A_current, x0, max_it, tol, verbose = verbose)

        vlastni_cisla.append(lambda_j)
        vlastni_vektory.append(q_j)

        if j == 0:
            print(f"\n--> Výsledek {j+1}. iterace deflace:")
            print(f"    λ = {lambda_j:.3f}")
            print(f"    q = {np.round(q_j, 3)}")

        A_current = A_current - lambda_j * q_j * q_j.T

        if j == 0:
            print(f"A deflovaná =\n{np.round(A_current, 3)}")
            print("____________________________________________________")


    return vlastni_cisla, vlastni_vektory

In [40]:
A = np.array([
    [2, 1, 0],
    [1, 3, 1],
    [0, 1, 2]
], dtype=float)

x0 = np.array([1, 0, 0])

vlastni_cisla, vlastni_vektory = deflation_method(A, x0, verbose = True)

print("_______________________________________________________")
print("Vlastní čísla a vektory:")
for i in range(3):
    print(f"Vlastní číslo {i + 1}: {vlastni_cisla[i]:.3f}")
    print(f"Vlastní vektor {i + 1}:")
    for val in vlastni_vektory[i]:
        print(f"  {val:.3f}")
    print("____________________________________________________")



--- VLASTNI CISLO 1 ---
Iterace 1:
    x = [2. 1. 0.]
    q = [0.894 0.447 0.   ]
    lambda_k = 3.000
Iterace 2:
    x = [2.236 2.236 0.447]
    q = [0.7  0.7  0.14]
    lambda_k = 3.667
Iterace 3:
    x = [2.1   2.941 0.98 ]
    q = [0.561 0.785 0.262]
    lambda_k = 3.909

--> Výsledek 1. iterace deflace:
    λ = 3.909
    q = [0.561 0.785 0.262]
A deflovaná =
[[ 0.77  -1.411 -0.268]
 [-0.23   0.589  0.732]
 [-1.23  -1.411  1.732]]
____________________________________________________
Iterace 1:
    x = [ 0.77 -0.23 -1.23]
    q = [ 0.524 -0.157 -0.837]
    lambda_k = 2.143
Iterace 2:
    x = [ 0.849 -0.826 -1.874]
    q = [ 0.383 -0.373 -0.845]
    lambda_k = 1.938
Iterace 3:
    x = [ 1.047 -0.926 -1.41 ]
    q = [ 0.527 -0.467 -0.71 ]
    lambda_k = 1.955
Iterace 1:
    x = [ 0.226 -0.774 -1.774]
    q = [ 0.116 -0.397 -0.91 ]
    lambda_k = 0.331
Iterace 2:
    x = [ 1.897  0.076 -0.156]
    q = [ 0.996  0.04  -0.082]
    lambda_k = 0.378
Iterace 3:
    x = [ 0.254 -0.743 -1.901