1. Naprogramujte v programovacím jazyce Python LUP rozklad matice A ∈ R^(n x n) s částečnou pivotizací například pomocí následujícího pseudokódu:

        for k = 1 : n - 1
            Determine μ with k ≤ μ ≤ n so |A(μ; k)| = ||A(k : n; k)|| oo
            A(k; k : n) ⇔ A(μ; k : n)
            p(k) = μ
            if A(k; k) ≠ 0
                rows = (k + 1) : n
                A(rows; k) = A(rows; k) / A(k; k)
                A(rows; rows) = A(rows; rows) - A(rows; k) * A(k; rows)
            end
        end

- **L** je **dolní trojúhelníková matice** (má čísla na diagonále a pod ní, nad diagonálou jsou nuly).
- **U** je **horní trojúhelníková matice** (má čísla na diagonále a nad ní, pod diagonálou jsou nuly).
- **P** je permutační matice** (říká nám, jestli a jak jsme prohazovali řádky v původní matici).

In [1]:
# importujte potřebnou knihovnu NumPy pod zkratkou np
import numpy as np

In [24]:
def LUP_rozklad(A):
    # Tvoje funkce LUP_rozklad(A) si nejprve udělá kopii matice A, aby neponičila tu původní,
    # a převede ji na desetinná čísla (float).
    # Pak zjistí její velikost (n) a vytvoří matici P jako jednotkovou matici stejné velikosti.
    A = A.copy().astype(float)
    n = A.shape[0]
    P = np.eye(n)

    print("Původní matice A:\n", A)
    print("_____________________________")

    # Tato smyčka probíhá pro každý sloupec matice (kromě posledního), kde se snažíme vynulovat prvky pod diagonálou.
    for k in range(n - 1):
        pivot_index = np.argmax(np.abs(A[k:n, k])) + k
        print(f"Krok {k +1} : pivot v řádku {pivot_index} pro sloupec {k}")

        if pivot_index != k:
            print(f"Prohazuji řádky {k} a {pivot_index}")
            A[[k, pivot_index], :] = A[[pivot_index, k], :]
            P[[k, pivot_index]] = P[[pivot_index, k]]
            print("A po prohození:\n", A)
            print("_____________________________")
            print("P:\n" ,P)
            print("____________________________")

        if A[k, k] != 0:
            for row in range(k + 1, n):
                A[row, k] /= A[k, k]
                A[row, k + 1:n] -= A[row, k] * A[k, k + 1:n]
            print("A po eliminaci:\n", A)
        print("_____________________________")

    L = np.tril(A, k = -1) + np.eye(n) #L: Vezme se dolní trojúhelník z A (bez hlavní diagonály, k=-1) a na diagonálu se dají jedničky.
    U = np.triu(A)
    return P, L, U


In [25]:
A = np.array([[4, 2, 1, 3],
              [3, 6, 2, 5],
              [2, 1, 3, 7],
              [5 , 9, 3, 8]], dtype=float)

P, L, U = LUP_rozklad(A)

Původní matice A:
 [[4. 2. 1. 3.]
 [3. 6. 2. 5.]
 [2. 1. 3. 7.]
 [5. 9. 3. 8.]]
_____________________________
Krok 1 : pivot v řádku 3 pro sloupec 0
Prohazuji řádky 0 a 3
A po prohození:
 [[5. 9. 3. 8.]
 [3. 6. 2. 5.]
 [2. 1. 3. 7.]
 [4. 2. 1. 3.]]
_____________________________
P:
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
____________________________
A po eliminaci:
 [[ 5.   9.   3.   8. ]
 [ 0.6  0.6  0.2  0.2]
 [ 0.4 -2.6  1.8  3.8]
 [ 0.8 -5.2 -1.4 -3.4]]
_____________________________
Krok 2 : pivot v řádku 3 pro sloupec 1
Prohazuji řádky 1 a 3
A po prohození:
 [[ 5.   9.   3.   8. ]
 [ 0.8 -5.2 -1.4 -3.4]
 [ 0.4 -2.6  1.8  3.8]
 [ 0.6  0.6  0.2  0.2]]
_____________________________
P:
 [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
____________________________
A po eliminaci:
 [[ 5.          9.          3.          8.        ]
 [ 0.8        -5.2        -1.4        -3.4       ]
 [ 0.4         0.5         2.5         5.5       ]
 [ 0.6        -0.11538

In [26]:
print("P:\n ", P)
print("_____________________________")
print("L:\n ", L)
print("_____________________________")
print("U:\n ", U)

P:
  [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
_____________________________
L:
  [[ 1.          0.          0.          0.        ]
 [ 0.8         1.          0.          0.        ]
 [ 0.4         0.5         1.          0.        ]
 [ 0.6        -0.11538462  0.01538462  1.        ]]
_____________________________
U:
  [[ 5.          9.          3.          8.        ]
 [ 0.         -5.2        -1.4        -3.4       ]
 [ 0.          0.          2.5         5.5       ]
 [ 0.          0.          0.         -0.27692308]]
